version: '3'
services:
  db:
    build: ./mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: lineschool
      MYSQL_DATABASE: kyotob
